# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMWn8orsbEVuJnZkrlUdRADCOEJCyIfS
"""

import pandas  as pd
data = {'students':['Balabarathi','silambarasan','pooja','Hari','prema'],
        'Marks':[78, 92, 55, 88, 70]}
df = pd.DataFrame(data)
df.to_csv('students.csv',index=False)
print("CSV created successfully")

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('students.csv')
print("All students data")
print(df)
print()
print("Average marks:", df['Marks'].mean())
print("Highest marks:", df['Marks'].max())
print("Lowest marks:", df['Marks'].min())

df